### ISSUE TITLE
Segfault when quiting with a dirty buffer

### ISSUE THREAD

**Issue by jorgensigvardsson** [troglobit/uemacs#3]
So, this is not an unknown bug, but I figured I should share some information about what I have found debugging the issue.

This is the callstack:
```
eputs(char* s)                                             echo.c:429
eformat(char* fp, char* buf, int nbuf, int flag, char* ap) echo.c:396
eread(char* fp, char* buf, int nbuf, int flag, char* ap)   echo.c:213
ereply(char* fp, char* buf, int nbuf, int arg)             echo.c:173
eyesno(char* sp)                                           echo.c:149
quit(int f, int n, int k)                                  main.c:172
execute(int c, int f, int n)                               main.c:103
main(int argx, char** argv)                                main.c:85
```

The line that segfaults is trying to dereference a pointer `s` holding a value of `0x40xxxxxxxx`. Tracing that variable back up through the stack trace, it should hold a pointer to the string "Quit". `quit` is semantically trying to do `printf("%s [y/n]? ", "Quit"); process_input();` The string `"Quit"` resides at `0x00005555555622ff` which is vastly different from `0x40xxxxxxxx`.

Tracing back through the stack trace, the call to `ereply` on line echo.c:149 seem to change the value:
```c
s = ereply("%s [y/n]? ", buf, sizeof(buf), sp);
```
where `sp` points to `"Quit"` does something to the pointer. On the callee side, the pointer is `0x555622ff`. I smell pointer truncation! So far, I have no idea why this is happening. Gotta get back to $DAYJOB now...

**Comment by jorgensigvardsson** [comment]
Ok, so I made a quick test by compiling uemacs as a 32 bit executable, and lo and behold: it works!

```
./configure --build=i686-pc-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
```

**Comment by jorgensigvardsson** [comment]
Maybe instruct users to build as a 32 bit executable? I wonder if there is a difference between ARM32 and ARM64. Do you have access to these architectures?

**Comment by jorgensigvardsson** [comment]
I think that this old style VARARG is invoking undefined behavior. If we look at x86 cdecl calling convention, arguments are pushed onto the stack, giving the callee sequential memory access to all parameters. The C code assumes this memory layout, and it does indeed work on x86.

x86-64 using the System V AMD64 calling convention generally doesn't pass arguments over the stack, but in registers. This breaks the C code, because the parameters just isn't on the stack - they're in registers!

No wonder it segfaults whenever the buffer is dirty - it is only then the user is queried whether to save the buffer(s) or not.

I see two solutions to this problem:
- Require x86 (or compatible cdecl calling convention - ARM doesn't seem to fit the bill: https://en.wikipedia.org/wiki/Calling_convention)
- Rewrite the VARARG like functions to use `va_*` macros in order to be portable

I'd love to have a shot at rewriting them, if you don't mind!

**Comment by troglobit** [comment]
Heh, yeah that explains it alright! Thank you for getting to the bottom of this! 😎✌️

Of course, go ahead and port to stdarg.h va_list et al instead! Should be fairly straightforward and not add to much overhead.

**Comment by jorgensigvardsson** [comment]
I have no idea how PRs and issues are linked on Github. I referenced the issue in the PR, hoping that would solve that problem. :)

This was fun! Is there more!? :)

**Comment by troglobit** [comment]
You can just put "Fix #3: description of fix" in the first line, or anywhere else even (I think) in the commit message to auto-close an issue when a PR is merged.  Anything else just pops up as a notification in the issue.

I'm sure we'll find more, maybe we should start using it as our daily driver?  And by that I mean for tasks like editing system files etc.  Usually I use Emacs (obviously! ;) for development and then vim when I edit system files, vim is the default editor in my Debian/Ubuntu/Mint installations (`sudo update-alternatives --config editor`).  If we add proper `debian/` packaging this could be handled automatically.  I can't seem to remember what system is your primary Linux distro, but maybe there are similar mechs in the RedHat/Fedora/SuSE world for .rpm's?

**Comment by troglobit** [comment]
I can do an initial packaging for Debian, if you like?

**Comment by jorgensigvardsson** [comment]
Hmm... know what would be fun? A Windows port. I use Linux on a daily basis, but that's mostly in VS Code with a bazillion extensions for Typescript/React and the like. Sure, uemacs could be used to edit the files, but I'd get pretty much nothing done. I do however use git command line in Windows (and to some extent in Linux too). I suppose as commit editor it would be good enough, and not hindering me in my day job. It would be kind of cool hosting uemacs in VS Code, whose backend is run on my Linux box and frontend in Windows.

Will look into a Windows port as soon as I've verified the code on OpenBSD (picked it from fond memories of yester~~day~~decade!).

**Comment by jorgensigvardsson** [comment]
What I mean is that I could probably use it as a daily driver for git commits on both platforms!

**Comment by troglobit** [comment]
Just tested on OpenBSD, NetBSD, FreeBSD, OmniOS, macOS, and DragonflyBSD ... only one that didn't start OK was DragonflyBSD.  This is why I looove GNU configure :-)

**Comment by troglobit** [comment]
A Windows port would be awesome! :-)

I guess mingw or cygwin would work right off the bat, but the regular cmd.exe ... dunno.  There could be some old useful code in https://github.com/troglobit/MicroEMACS/blob/master/src/termio.c <-- grep for MSDOS, other files in that repo may also be useful

**Comment by jorgensigvardsson** [comment]
I just had a battle with OpenBSD 6.8. It does not have `sgtty.h`, so it failed to compile for me. If I just removed the `#include <sgtty.h>` it just compiled. Is that what you did?

Anyway, no need to dig around in the OpenBSD then! I'll get straight to the Windows port, that'll be fun! The MSDOS stuff won't do me any good, as the console API for Windows is totally different. It looks like MSDOS stuff in the MicroEMACS repo really is _MS-DOS_. Lot's of interrupt calls into and the like. Windows has a more C-like API. Haven't messed with it much at all, so this'll be fun! I just hope I get the K&R syntax past the Microsoft compiler... 🌦️

**Comment by jorgensigvardsson** [comment]
Well. Windows has a _C API_, it just isn't like one. It is one. 😄

**Comment by troglobit** [comment]
Yeah, i did that and a few other things. Check the log :)

Cool, really looking forward to your port!
