### ISSUE TITLE
Windows port requested

### ISSUE THREAD

**Issue by jorgensigvardsson** [troglobit/uemacs#5]
Filing this is an issue, will send a PR for it sooner or later.

### Status so far
Got an nmake-file setup in the Windows-port. Have three nuts to crack:
- Figure out what to do with itoa which is a defined function in the Windows C runtime (it's also defined in `buffer.c`, but with different semantics and parameters)
- Figure out how to do the tty-like operations (added `tty/windows-console`). Looks kind of straightforward.
- Figure out how to do the sys-backend - looks straightforward. Wonder though how we'll handle CRLF.

**Comment by jorgensigvardsson** [comment]
Branch for tracking: https://github.com/jorgensigvardsson/uemacs/tree/port/windows

**Comment by troglobit** [comment]
Maybe a define hack for itoa would work?

**Comment by jorgensigvardsson** [comment]
I thought about that, but I don't see how I could get away within without changing the original source code. `stdlib.h` is included in the file that defines `itoa`. I ended up renaming it to `itoa_` for now.

In other news: it now starts on Windows. Terminal sizes are hardcoded for now (80x25), as the function in Windows for querying that information is not what you'd expect. Haven't deciphered it yet, but it's on my immediate TODO-list.

Next up is to implement tty functionality so that users actually can interact with the editor. Minor detail.

I have also not decided whether to use nmake (Microsoft's make) or vcbuild (XML-based format). The former is easy enough to tweak for anyone with a bit of make knowledge. The latter is better as it's dead simple to use in Visual Studio (editing, debugging, configuration, etc). I'm leaning towards the latter. I figure that if anyone has any interest in Windows and is building from source, they'd most likely know about vcbuild. I'd dare say that everyone that knows how to use nmake, knows how to use vcbuild. The reverse is probably not true. For now I'm using both. :)

**Comment by jorgensigvardsson** [comment]
![image](https://user-images.githubusercontent.com/6490309/99411287-b5f79e00-28f3-11eb-89ee-a05281cd25c7.png)
It's displaying something! Still have to work on both output and input. Turns out the console has virtual terminal support (https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences). Maybe I can reuse a lot!

**Comment by troglobit** [comment]
NICELY DONE! :grinning: 

Yeah, that looks like plain old escape sequences, VT100 and ANSI.  Should be fairly portable, cool!

**Comment by jorgensigvardsson** [comment]
Ok, so CTRL+C handling is now fixed. Turns out that when using `ENABLE_VIRTUAL_TERMINAL_INPUT` as console input mode, Windows does not signal the process to die when you hit CTRL+C. That's good - no messy signal handling needed.

Now I just have to figure out why the entire buffer is redrawn all the time. I did read an example somewhere, where a screen buffer was utilized. Now I just need to figure out how to use it. Nearly done now, and then do some refactoring/cleanup of the mess I have left in my wake. :)

**Comment by jorgensigvardsson** [comment]
Well what do you know!? The original screen buffer worked just fine

**Comment by jorgensigvardsson** [comment]
Now figuring out why:
- Initial screen refresh/draw won't happen (screen is refreshed as soon as I hit any key)
- Remap some Windows virtual escape codes (notably home and end) to "real" VT codes

End in Windows: `<esc>[F`
End in Linux: `<esc>[4~`

Home in Windows: `<esc>[H`
Home in Linux: `<esc>[1~`

What else differs?

**Comment by jorgensigvardsson** [comment]
I found a somewhat ackward bug. In `ttyio.c` terminal size is defined by `nrow` and `ncol`. In `tty/{ansi,windows-console}/ttydef.h` there are two `#defines`: NROW and NCOL. If they don't match `nrow` and `ncol` respectively, I get weird screen updates. The initial update is totally fubar for me in Windows, and after that I get oddities whenever the mode line changes, or when I scroll the buffer.

Not sure how to get around this. Compile time constants don't go hand in hand with user defined terminal sizes. Not really sure what to do here without modifying the original sources. I'm guessing this is from a time when terminal sizes were fixed.

There is one possibility, and that is to compile the application into a win32 application rather than a console application, and then open a console manually, specifying the size of the console. The downside of that is that it will open the standard Windows console (I like Windows Terminal far better), and I'm not quite sure how it will react with other tools such as `git`.

I will also investigate if I can resize the terminal at startup, so that we enforce that `NROW == nrow && NCOL == ncol`.

**Comment by jorgensigvardsson** [comment]
Very near a somewhat decent port to Windows. Just have to implement spawncli (looks easy enough on the surface).

I have also tested uemacs in both 32 and 64 builds, and there seems not be any stupid pointer hacks that ruins the day.

**Comment by jorgensigvardsson** [comment]
BTW, found a way to force the terminal size to be 132x50 on Windows, and adjusted NROW and NCOL accordingly. Although, the newer Windows Terminal does not respect resetting the original buffer size on exit. Not sure why that is - bugs most likely, as it's a fairly new tool. The standard windows console handles it just fine.

**Comment by troglobit** [comment]
Ran into similar problems with the Unix port when I had too big terminal I did a workaround in that port by just limiting the size to the max of NROW and NCOL.  I noiticed these limitations are not part of the Daniel Lawrence v3.6 (based on this) version, so I guess even back in 1986 they fxed that limitation :)
